// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Конфигурация по умолчанию для Firebase для приложения IntelectualPath
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVf8YvuCWZ5crDTl1ZiFT-yI5hQe0GFU',
    appId: '1:462772008865:web:327923dba2a6d70d49fde0',
    messagingSenderId: '462772008865',
    projectId: 'intelectualpathv2',
    authDomain: 'intelectualpathv2.firebaseapp.com',
    databaseURL: 'https://intelectualpathv2-default-rtdb.firebaseio.com',
    storageBucket: 'intelectualpathv2.firebasestorage.app',
    measurementId: 'G-1DGF33YNF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQS-WafK7rZLksFRxAzlSZjcShTxRIEmE',
    appId: '1:462772008865:android:205c2d675f6f000f49fde0',
    messagingSenderId: '462772008865',
    projectId: 'intelectualpathv2',
    databaseURL: 'https://intelectualpathv2-default-rtdb.firebaseio.com',
    storageBucket: 'intelectualpathv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_LIy7GYS63u1ADdoOUNq1WnnjO6JyK0',
    appId: '1:462772008865:ios:274de77a9d0c3dff49fde0',
    messagingSenderId: '462772008865',
    projectId: 'intelectualpathv2',
    databaseURL: 'https://intelectualpathv2-default-rtdb.firebaseio.com',
    storageBucket: 'intelectualpathv2.firebasestorage.app',
    iosBundleId: 'com.example.intelectualPathV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_LIy7GYS63u1ADdoOUNq1WnnjO6JyK0',
    appId: '1:462772008865:ios:274de77a9d0c3dff49fde0',
    messagingSenderId: '462772008865',
    projectId: 'intelectualpathv2',
    databaseURL: 'https://intelectualpathv2-default-rtdb.firebaseio.com',
    storageBucket: 'intelectualpathv2.firebasestorage.app',
    iosBundleId: 'com.example.intelectualPathV2',
  );
}
